### ISSUE TITLE
Add features and tests to `AxialVector`

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#1]
The `AxialVector` type is currently very incomplete. It should implement all fitting traits from `cgmath`, overload many operators and add a few more methods:

- add `unit_q()` and `unit_r()` (like `unit_x()` from `cgmath::Vector2`)
- overload many useful operators (including `Index`, required by `Array` anyway)
- implement `cgmath::{Zero, Array, MetricSpace, VectorSpace, InnerSpace}`

Everything should be done similar to [cgmath::Vector2](http://bjz.github.io/cgmath/cgmath/struct.Vector2.html).

Additionally multiple unit tests should be added to ensure correctness.

*Note*: this issue is similar to #2

**Comment by Cranc** [comment]
implement ops::{Add, Mull, Sub, Div}
