### ISSUE TITLE
Add features and tests to `AxialPoint`

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#2]
The `AxialPoint` type is currently very incomplete. It should implement all fitting traits from `cgmath` and overload many operators:

- overload many useful operators (including `Index`, required by `Array` anyway)
- implement `cgmath::{Zero, Array, MetricSpace, VectorSpace, InnerSpace}`

Everything should be done similar to [cgmath::Point2](http://bjz.github.io/cgmath/cgmath/struct.Point2.html).

Additionally multiple unit tests should be added to ensure correctness.

*Note*: this issue is similar to #1

**Comment by FischerTo** [comment]
cgmath::InnerSpace is not going to be implemented.

**Comment by jonas-schievink** [comment]
Makes sense, it's meant for vectors, not points

**Comment by FischerTo** [comment]
Zero and VectorSpace are also not required, as they are implemented in axial_vector.rs
