### ISSUE TITLE
Git credential.helper Fehler

### ISSUE THREAD

**Issue by RastaTux** [OsnaCS/plantex#201]
Beim builden bekomme ich einen Git-Fehler. Anfangs hieß es, dass credentials.username nicht gelesen werden kann. Durch diverses herumexperimentieren ging es über credentials.https;//github.com.username und credentials.https://github.com.jonas-schievink/glium.git.username bis zu der folgenden Meldung:

```  plantex cargo build --release --verbose                                                                
    Updating git repository `https://github.com/jonas-schievink/glium.git`
error: failed to load source for a dependency on `glium`

Caused by:
  Unable to update https://github.com/jonas-schievink/glium.git?branch=unifast#c062d206

Caused by:
  failed to fetch into /home/******/.cargo/git/db/glium-1d278ab6db4cdf7b

Caused by:
  failed to authenticate when downloading repository
attempted to find username/password via git's `credential.helper` support, but failed

Caused by:
  [0/-1] an unknown error occurred
```

Gibt es die Möglichkeit, die dependencies manuell herunterzuladen? Irgendwas mit den github credentials scheint da verdröselt zu sein...

**Comment by LukasKalbertodt** [comment]
@jonas-schievink your fork seems to be deleted?

**Comment by jonas-schievink** [comment]
Uh, oops. We should update to upstream glium, my changes have been merged.

Also, what a bad error message.

**Comment by RastaTux** [comment]
Yeah, the error message really confuzed me. So i changed the dependency to tomaka/glium repo and master branch, now i get another error. :(
```   Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `x11-dl` (required by `winit`):
all possible versions conflict with previously selected versions of `x11-dl`
  version 2.7.0 in use by x11-dl v2.7.0
  possible versions to select: 2.12.0, 2.11.0, 2.10.0, 2.9.0, 2.8.0
```
