### ISSUE TITLE
glium dependency has a broken link

### ISSUE THREAD

**Issue by kalabukdima** [OsnaCS/plantex#202]
Repository https://github.com/jonas-schievink/glium.git doesn't exist, but `client` has it as a dependency.

**Comment by jonas-schievink** [comment]
You can apply this to fix it:
```diff
diff --git a/client/Cargo.toml b/client/Cargo.toml
index 8b67d139..1b6a21e1 100755
--- a/client/Cargo.toml
+++ b/client/Cargo.toml
@@ -11,13 +11,10 @@ clap = "2"
 toml = "0.1"
 regex = "0.1"
 rand = "0.3"
+glium = "0.15"
 
 [dependencies.base]
 path = "../base"
 
-[dependencies.glium]
-git = "https://github.com/jonas-schievink/glium.git"
-branch = "unifast"
-
 [dependencies.noise]
 git = "https://github.com/bjz/noise-rs"
```

You also need to build with an old Rust version:
```
cargo +1.10.0 run --bin plantex
```

**Comment by kalabukdima** [comment]
Oh, it works with an old Rust compiler. Thanks!
But, unfortunately, it doesn't compile with a new one.

**Comment by LukasKalbertodt** [comment]
@kalabukdima This issue is now fixed on master. The current master compiles with the current stable compiler.

**Comment by kalabukdima** [comment]
Cool. Thanks!
