### ISSUE TITLE
Basic world generation

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#3]
We need some very basic world generation... something like `sin`-mountains :smile_cat: 
The world should be generated on the fly, depending on the players position.

**Comment by jonas-schievink** [comment]
You can use the [`rand`](https://crates.io/crates/rand) crate ([documentation](https://doc.rust-lang.org/rand/rand/index.html)) for random number generation (you'll probably use [`XorShift`](https://doc.rust-lang.org/rand/rand/struct.XorShiftRng.html)).

**Comment by LukasKalbertodt** [comment]
Done in #33 and #44
