### ISSUE TITLE
Tracking issue: sky rendering

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#53]
This issue is about rendering the sky box. A detailed German description can be found [here](https://lukaskalbertodt.gitbooks.io/cgp16-tasks/content/himmel_und_atmosphare.html).

Probably the first thing that should be implemented is a type that manages all properties of the sky, like the position of the sun. This is needed for other groups as well, e.g. for lightning and shadows.

(this issue will probably expanded in the future)

**Comment by jonas-schievink** [comment]
@jbesteuos is also looking into this, I'll assign him, too

**Comment by LukasKalbertodt** [comment]
@jonas-schievink Sure, feel free to assign people I forgot. I just suck at remembering names :P

**Comment by LarsHachmeister** [comment]
A maybe helpful Link:
http://www.flipcode.com/archives/Sky_Domes.shtml

**Comment by jonas-schievink** [comment]
This is done (and looks awesome)!
