### ISSUE TITLE
Dynamic chunk loading and unloading

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#55]
Currently, a fixed number of chunks at a fixed position is loaded. We need a system that dynamically loads and unloads chunks depending on the position of the player/ghost. This unloading probably only needs to happen for `ChunkView`s ... the `Chunk`s don't occupy a lot of RAM and aren't drawn without corresponding `ChunkView`, so they can stay. Of course if a chunk is not even generated as a `Chunk`, this needs to happen, too.

Additionally there should be some clever distance based measure to unload/load chunks. While it is easier to always load neighbor chunks, the strange shape of our chunks makes it rather inefficient. Two corners of the rhombus are very far away from the player (we don't really need to load them) while the other two corners are pretty close. So the algorithm should load every chunk which is less than n meters away, measured in world coordinates.

**Comment by jonas-schievink** [comment]
Marking as `D-hard` since I struggled to find a satisfying solution within the last days (I'd love to be proven wrong, though)
