### ISSUE TITLE
Create the vertex buffer layout of hex pillars with correct normals

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#60]
Currently the normals in the vertex buffer are not well suited for flat shading. We need to replace those with proper normals, by adding more vertices. Sadly we need multiple vertices for the same point in space, but with different normals. Specifically: for each point in space we need exactly three vertices, one for each face this point is a corner of.

**Comment by jonas-schievink** [comment]
> Currently the normals in the vertex buffer are not well suited for flat shading.

There are no normals in the vertex buffer, the "lighting" is just a pretty... interesting calculation in the vertex shader.

**Comment by LukasKalbertodt** [comment]
Oh, but I think they had normals in the buffer before... But let's put it this way: the vertices are not well suited for flat shading because we can't just add a normal to each vertex, but must duplicate vertices.

**Comment by LukasKalbertodt** [comment]
Done in #78

**Comment by jonas-schievink** [comment]
In #83 ;)
