### ISSUE TITLE
Think about terrain smoothing

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#62]
While #61 is only about the performance aspect and has no effect on the visuals, we should decide in the team whether or not to use terrain smoothing. By that term I mean: whenever two hex pillars differ only a little in height, we smooth out the terrain by connecting points of both pillars to create a slope. Note that this smoothing is purely a graphical feature: the representation of the world (in `base`)  doesn't change!

Technically speaking, the advantage is that we could decrease the vertex count by a noticeable amount while the disadvantage is that implementing terrain smoothing is probably pretty hard/tricky.

But as said, this also has a big visual impact. With terrain smoothing, the terrain would look a lot more like terrain in other games and the hexagon shape would be less prominent in the world. The player would still see many hexagon shapes in the game, but not as much, obviously. Whether or not we want terrain smoothing needs to be discussed in the group. A gameplay advantage of terrain smoothing is that the player could easily see whether he can just walk up a hill or needs to jump.

Personally, I think we should use terrain smoothing. A realistic world with a few nice hexagons will look pretty nice IMO.

**Comment by jonas-schievink** [comment]
Hrrrmmm really not sure if I want this...

> the advantage is that we could decrease the vertex count by a noticeable amount

That's not necessary, the world should consist of less vertices than a Minecraft world, and we can do loads of other optimizations like instancing before we need to consider this as an optimization.

A disadvantage is that this conflicts with instancing and means that we'll have to build geometry for every chunk (now we at least have the option of using a single vertex buffer for all hex pillars).

This makes me think that this will actually be bad for performance... Hmm.

> A gameplay advantage of terrain smoothing is that the player could easily see whether he can just walk up a hill or needs to jump.

*This* could be nice if done correctly!

We might want to do this after the 3 weeks. The game will look really nice even without, and we have loads of other tricky issues to work on.

**Comment by LukasKalbertodt** [comment]
I've been thinking and I *think* I agree that we should first use instancing to increase performance instead of creating one big vertex buffer. The advantage is probably that it's way easier to manipulate a chunk without regenerating all buffers. 

Then #61 would be only necessary specifically for terrain smoothing. And I agree that we might want to postpone it, because it's really tricky: I just noticed that we need neighbor chunks, too, to do proper terrain smoothing.

In regards to performance: I'm not convinced that instancing will have a greater performance than one big vertex buffer -- I rather think the opposite is. But as I said: the instancing solution has many other advantages so now I'm in for "instancing now, terrain smoothing with one big vertex buffer maybe later".

But again: we should ask everyone on Monday.

**Comment by LukasKalbertodt** [comment]
The group decided to postpone this.
