### ISSUE TITLE
Fancy iterators over chunks and pillars

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/plantex#64]
Currently, we can use `Chunk::pillars()` to get a slice over all pillars, but this is hardly used, because the pillar itself don't know where it's positioned in the world. Therefore we often have two nested for loops in user code.

I want a `pillars()` method that returns an iterator over the item `(AxialVector, &HexPillar)`. A vector instead of a point, because it's not the world position. Or maybe `PillarPosition` ... I lost track of all axial position types we have :stuck_out_tongue:  

The same applied to the `World` type: we maybe want to iterate over all chunks while also knowing the chunk position.

**Comment by HelenaKeller** [comment]
Andy and I would take this issue.

**Comment by LukasKalbertodt** [comment]
Done in #93
