### ISSUE TITLE
Implement AxialPoint::from_real

### ISSUE THREAD

**Issue by jonas-schievink** [OsnaCS/plantex#68]
We need to convert world coordinates to axial coordinates to be able to figure out the player position (or any object's position) in pillar/chunk coordinates to implement things like #55, so this has very high priority at least for world gen.

http://www.redblobgames.com/grids/hexagons/#pixel-to-hex

`pub fn from_real(real: Point2f) -> Self`

(this doesn't have much to do with world gen, but I tagged it `S-gen-world` anyways because it's basically blocked on this)

**Comment by 92Andy** [comment]
I would like to work on this issue ;)
