### ISSUE TITLE
Fix wrong indexing of Inner_Position

### ISSUE THREAD

**Issue by JonasKnerr** [OsnaCS/plantex#98]
`inner_pos.q` and `inner_pos.r`, two chunk indices, are somehow switched. The method called is at
`base > src > world > world.rs` in `pillar_at`, line 40. It is temporarily patched at lines 53-58.
Please find the mysterious origin of the switched indices and fix it at the source.

**Comment by jonas-schievink** [comment]
Don't forget to add a regression test when fixing this :)
